### ISSUE TITLE
Update annotated image for NestedList component

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-manual#1]
`NestedList` component has some [changes](https://github.com/appbaseio/reactivebase/issues/28) related to styling. The image needs an update in accordance.

* Besides, it also has a search container just like the SingleList. We should use that in the image.

![Image](https://i.imgur.com/Gh0iVDb.png)

**Comment by metagrover** [comment]
Fixed here d93f6713c9272fd96dbaf312628d0215c276a085
