### ISSUE TITLE
Codepen is broken

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactive-manual#15]
Need to update codepen in [NestedList](https://opensource.appbase.io/reactive-manual/v1.0.0/search-components/NestedList.html)
Also in [CategorySearch](https://opensource.appbase.io/reactive-manual/v1.0.0/search-components/CategorySearch.html)
Probably needs update in all codepens

ReactiveSearch umd link has to be updated

**Comment by siddharthlatest** [comment]
@divyanshu013 what is missing here now?

**Comment by divyanshu013** [comment]
Works now!
