### ISSUE TITLE
Document v2 major changes and prop updates

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactive-manual#47]
# Props Changes

- [x] **customQuery**: callback would receive the updated props in addition to the updated value. The function definition would be `(value, props)`. Also allow for extending the use case by using useful props like `fuzziness`, `fieldWeights` directly in the callback to generate custom query.

- [x] <s>**componentId**: we're using certain internal components which end with `__internal`. We should mention this. If the user sets this on a reactive component, the filter values and URL params won't be set for that component</s> Not mentioning in docs

- [x] **pagination**: the issue with infinite loading in `ReactiveList` (native) is that there should be enough components to make the list scrollable. Need to think more on this subject

- [x] **queryFormat**: document the different date formats supported via this prop in date components

- [x] **fieldWeights**: the prop name changes for both `weights` and `searchWeight`

- [x] **showFilter** and **filterLabel**: will update only when the underlying query changes

- [x] **queryFormat**: will only update the query when there's a change in the selected items (eg -
 `MultiList`)

- [x] **title**: Remove `title` prop in actuators

- [x] **range**: prop is not optional

- [x] **placeholder**: remove `placeholder` prop in actuators

- [x] **debounce**: new prop for text input based components like TextField, DataSearch, CategorySearch

- [x] **beforeValueChange**: the components goes in a locked state when `beforeValueChange` is present so any changes to the component's state are ignored. `beforeValueChange` should be used with care since a long resolving function can block the user interaction with the component.

# New Components

- [x] **RangeInput**: is a new component which extends the functionality of `RangeSlider`. Add docs for it.

- [x] **ReactiveComponent**: add docs

# Components updates

- [x] **NumberBox**: accepts no props for filters. `showFilter` and `filterLabel` will not work therefore

- [x] **RangeSlider**: accepts no props for filters. `showFilter` and `filterLabel` will not work therefore

- [x] **RangeSlider**: provides a `snap` prop which uses the `stepValue` to snap the slider in position. Defaults to `true`. When set to `false`, the slider doesn't use the `stepValue`

- [x] **SelectedFilters**: update the docs

- [x] **DatePicker**: update the docs

- [x] **DateRange**: update the docs

- [x] **SelectedFilters**: props

- [x] **ToggleButton**: now expects a `string` or `array` in `defaultSelected` depending on `multiSelect` value

- [x] **ReactiveList**: `onAllData` prop update

# Concepts

## Theming

- [x] Theming concepts have changed, we now use a `ThemeProvider` from `emotion` which makes it easy to overwrite/add styles easily using `ReactiveBase`. Add docs related to these.

- [x] For extending component styles each component accepts an object which applies the provided `className`. Document the `innerClass` object for all components

- [x] Notes on specificity so the custom styles have higher preference. For ref - https://material-ui-next.com/customization/overrides/

- [x] Can we use `withTheme` from emotion for react components which are children of `ReactiveBase`?

## Proxying
- [x] server request via a middleware

## Final Review

- [x] Review all props with v2 code

**Comment by metagrover** [comment]
- [x] We have removed `initialLoader` from all sensors and renamed `initialLoader` to `loader` in all actuators. 

- [x] `loader` accepts string or valid JSX.

**Comment by metagrover** [comment]
### Actuators:

- [x] onAllData() takes two parameters - items and a callback function which should be called when the result list reaches the end (on scroll).

- [x] Note that callback function will only be executed in case of infinite loading

```
onAllData(items, loadMoreData) {
	// return the list to render
}
```

- [x] We now append `stream: true` key to the streaming hit objects - in order to allow users to selectively react to the streaming changes. 
**Appropriate use-cases:** FadeIn animation on new streaming hits; Twitter/Facebook like streams showing the count of new feed items available (2 New Tweets)

- [x] Instead of `desc` we use `description` now

**Comment by metagrover** [comment]
- [x] DataController does not support `dataLabel` prop anymore. Instead, it is a HOC and renders the children passed to it.

**Comment by metagrover** [comment]
### Class/Style injection

- [x] Support for innerClass prop across all components:

```
<ComponentName
	innerClass = {{
		title: <className>,
		label: <className>,
		button: <className>,
		input: <className>,
		list: <className>,
		resultStats: <className>,
		pagination: <className>
	}}
/>
```

**Comment by metagrover** [comment]
- [x] Add `target` prop documentation in ResultCard and ResultList. This prop is valid in case of URLs.

**Comment by siddharthlatest** [comment]
@divyanshu013 Can you review this issue, do we still need to update some of the props in the docs?

**Comment by divyanshu013** [comment]
There is still some stale content in the docs
