### ISSUE TITLE
React-Native: Add Documentation

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-manual#65]
- [x] <s>We need to create a version switcher for React Native.</s> Using a different repo

- [x] Getting Started Section
   - [x] Install and Quickstart
   - [x] Import Data
   - [x] ReactiveBase
   - [x] Components Overview
- [x] Component References
    One doc per component
- [x] Advanced 
    - [x] Add a snack snippet for the ReactiveComponent doc.
    - [x] Performance Tips @metagrover 
    - [x] <s>Creating Themes, Styles</s> Unsupported in current version

**Comment by divyanshu013** [comment]
- [x] Link to the advanced section in reactive-manual for common concepts such as `customQuery`, `react` prop, writing and editing data and comparison with other projects
- [x] **Advanced** reactive component for native
- <s>**Advanced** running outside expo environment (fonts, builds, etc.)</s>

**Comment by siddharthlatest** [comment]
- [x] Link `innerStyle` to all the components
- [x] Link `innerProps` to all the components
- [x] Update `theming` prop for ReactiveBase.
- [x] Talk about innerStyle in [Customizing Style doc](https://opensource.appbase.io/reactive-manual/native/advanced/style.html).

**Comment by siddharthlatest** [comment]
- [ ] Add a doc on how to publish the app - With expo and as an ejected app @siddharthlatest
- [x] SelectedFilters doc @divyanshu013
