### ISSUE TITLE
native: innerStyle prop docs

### ISSUE THREAD

**Issue by dhruvdutt** [appbaseio/reactive-manual#70]

**Comment by metagrover** [comment]
- [x] Add `theme` prop docs in `ReactiveBase`

**Comment by divyanshu013** [comment]
Resolved via https://github.com/appbaseio/reactive-manual/commit/704067e2b6fadf1829a6fe23264914e14b253d2d https://github.com/appbaseio/reactive-manual/commit/b98306a32f4d69d64a0b202ff131be00be4165e4 https://github.com/appbaseio/reactive-manual/commit/0fc89b13705245b11db3e76cb1cc493c086614e6 https://github.com/appbaseio/reactive-manual/commit/5b3f759335635be900df82edbcd166dc52ebe804
