### ISSUE TITLE
Native: Missing Props

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/reactive-manual#71]
- DatePicker
  - [ ] Why do we have `showFilter` and `filterLabel` props? [Code Ref](https://github.com/appbaseio/reactivesearch/blob/dev/packages/native/src/components/date/DatePicker.js#L340-L341) - these are missing from the doc.

**Comment by divyanshu013** [comment]
These are present in all the components. They'll work if/when we add a `SelectedFilters` like component in native.
