### ISSUE TITLE
Improve streaming docs

### ISSUE THREAD

**Issue by divyanshu013** [appbaseio/reactive-manual#75]
The docs on streaming are not very clear about how streaming works in ReactiveSearch's context. For example, when would `results` update and when would `streamResults` update. Some examples would be helpful in understanding this concept with some recipes on handling CUD in the results components.

As a starting point, explaining a TODO app with CUD should suffice.

**Comment by siddharthlatest** [comment]
@divyanshu013 Do we have this updated now?
